# oc apply -f dgrade_metallb_operator.yaml
# oc get installplan -n metallb-system
# oc patch installplan <install-plan-name> -n metallb-system --type merge -p '{"spec":{"approved":true}}'

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator
  namespace: metallb-system
spec:
  channel: stable
  installPlanApproval: Manual 
  name: metallb-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: metallb-operator.4.12.0.202401291234
